<?php

namespace wind\acm;

use Yii;
use yii\helpers\Inflector;
use yii\helpers\ArrayHelper;

/**
 * GUI manager for RBAC.
 *
 * Use [[\yii\base\Module::$controllerMap]] to change property of controller.
 * To change listed menu, use property [[$menus]].
 *
 * ```
 * 'layout' => 'left-menu', // default to null mean use application layout.
 * 'controllerMap' => [
 *     'assignment' => [
 *         'class' => 'mdm\admin\controllers\AssignmentController',
 *         'userClassName' => 'app\models\User',
 *         'idField' => 'id'
 *     ]
 * ],
 * 'menus' => [
 *     'assignment' => [
 *         'label' => 'Grand Access' // change label
 *     ],
 *     'route' => null, // disable menu
 * ],
 * ```
 *
 * @property string $mainLayout Main layout using for module. Default to layout of parent module.
 * Its used when `layout` set to 'left-menu', 'right-menu' or 'top-menu'.
 * @property array  $menus      List avalible menu of module.
 * It generated by module items .
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since  1.0
 */
class Modules extends \yii\base\Module
{
    
    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'wind\rest\controllers';
    
    /**
     * @var array
     * @see [[items]]
     */
    private $_normalizeMenus;
    
    /**
     * @var string Default url for breadcrumb
     */
    public $defaultUrl;
    
    /**
     * @var string Default url label for breadcrumb
     */
    public $defaultUrlLabel;
    
    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
    }
}
